In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('covid_dataset.csv')
df

     Age  Gender  Fever   Cough       City Has_Covid
0     56    Male  102.4    Mild     Mumbai        No
1     19  Female  101.6  Strong     Mumbai        No
2     76  Female  102.0    Mild    Kolkata        No
3     65    Male   99.7    Mild  Bangalore        No
4     25  Female  102.1    Mild      Delhi       Yes
..   ...     ...    ...     ...        ...       ...
995   41    Male  102.0    Mild     Mumbai        No
996   76  Female  100.9    Mild      Delhi        No
997   35    Male  100.6    Mild    Kolkata        No
998   13  Female   99.5    Mild    Kolkata       Yes
999   55  Female  102.7  Strong    Kolkata       Yes

[1000 rows x 6 columns]

In [3]:
df.head()

   Age  Gender  Fever   Cough       City Has_Covid
0   56    Male  102.4    Mild     Mumbai        No
1   19  Female  101.6  Strong     Mumbai        No
2   76  Female  102.0    Mild    Kolkata        No
3   65    Male   99.7    Mild  Bangalore        No
4   25  Female  102.1    Mild      Delhi       Yes

In [4]:
df.size

6000

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.drop(columns=['Has_Covid']),df['Has_Covid'],test_size=0.2)

In [6]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [7]:

trans=ColumnTransformer(transformers=[
    ('tanf1',SimpleImputer(),'Fever'),
    ('tanf2',OrdinalEncoder(categories=[['Mild','Strong']]),['Cough']),
    ('tanf3',OneHotEncoder(drop='first'),['Gender','City'])

],remainder='passthrough')

In [8]:
trans.fit_transform(X_test).shape

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.